### ISSUE TITLE
Breast Center does not confer appointments

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/JenaConnectifier#1]
This user is listed as being in the Breast Center, but this should be linked to the Ophthalmology department.
http://vivo.med.cornell.edu/individual/cwid-chsung

There are other users for whom this is also a problem.

**Comment by sarbajitdutta** [comment]
This is fixed. I see the linking to Ophthalmology dept. Do check and let me know if there is other users who are having the same issue and their cwid.

**Comment by paulalbert1** [comment]
I'm still seeing Breast Center appointments. This is fixed on stage but not production. When will this be fixed on production?

![image](https://user-images.githubusercontent.com/3651640/55883922-29acc300-5b75-11e9-8596-11115781bac4.png)

**Comment by sarbajitdutta** [comment]
> I'm still seeing Breast Center appointments. This is fixed on stage but not production. When will this be fixed on production?
> 
> ![image](https://user-images.githubusercontent.com/3651640/55883922-29acc300-5b75-11e9-8596-11115781bac4.png)

Checking into this. Could be a where a user modified the org-u24 to have label of breast center or have multiple label? I checked ASMS where we are getting org units there is no Breast Center for department and id 24 is related to Ophthalmology

**Comment by sarbajitdutta** [comment]
This will be fixed after deleting wcmcVivo graph.
