### ISSUE TITLE
Update info from InfoEd when it changes

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/JenaConnectifier#5]
** UPDATED
cwid
begin_date
edn_date

** PK
account_number

** NOT UPDATED
award_number
proj_title
unit_name
int_unit_code
orig_sponsor
subaward_sponsor
spon_code

***
The grant with Account_Number = `0000015610` has been updated to have sponsor = `Patient-Centered Outcomes Research Institute`

In VIVO, it's listed as `Epilepsy Foundation`.
http://vivo.med.cornell.edu/display/grant-0000015610

![image](https://user-images.githubusercontent.com/3651640/56078981-0c1d6a80-5dbc-11e9-918c-4c20b70cd5c2.png)

**Comment by sarbajitdutta** [comment]
Why was this use case not addressed while designing it? I thought sponsor cannot be updated.

**Comment by paulalbert1** [comment]
We asked what info would change. Sponsor was not included in that list. Sorry we didn't catch this from the outset. We try to use your time as wisely as possible. This is frustrating to me too.
